# Generated by Django 5.0.1 on 2025-11-05 08:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminFeeConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_percentage', models.DecimalField(decimal_places=2, default=10.0, help_text='Percentage fee charged on survey campaigns (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SurveyCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('target_participants', models.PositiveIntegerField(default=100)),
                ('reward_per_participant', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('participant_count', models.PositiveIntegerField(default=0)),
                ('completed_responses', models.PositiveIntegerField(default=0)),
                ('total_tokens_awarded', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('admin_fee_collected', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('survey_config', models.JSONField(blank=True, default=dict)),
                ('eligibility_criteria', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('launched_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignReward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('admin_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('net_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_rewards', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='surveys.surveycampaign')),
            ],
        ),
        migrations.CreateModel(
            name='CampaignParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('started', 'Started'), ('completed', 'Completed'), ('abandoned', 'Abandoned'), ('disqualified', 'Disqualified')], default='invited', max_length=20)),
                ('survey_responses', models.JSONField(blank=True, default=dict)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_participations', to=settings.AUTH_USER_MODEL)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='surveys.surveycampaign')),
            ],
        ),
        migrations.AddIndex(
            model_name='surveycampaign',
            index=models.Index(fields=['status', 'created_at'], name='surveys_sur_status_d1360f_idx'),
        ),
        migrations.AddIndex(
            model_name='surveycampaign',
            index=models.Index(fields=['creator', 'status'], name='surveys_sur_creator_7e3724_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignreward',
            index=models.Index(fields=['status', 'created_at'], name='surveys_cam_status_0969ec_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignreward',
            index=models.Index(fields=['campaign', 'status'], name='surveys_cam_campaig_5147e6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignreward',
            unique_together={('campaign', 'participant')},
        ),
        migrations.AddIndex(
            model_name='campaignparticipant',
            index=models.Index(fields=['campaign', 'status'], name='surveys_cam_campaig_33b36a_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignparticipant',
            index=models.Index(fields=['participant', 'status'], name='surveys_cam_partici_e346aa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='campaignparticipant',
            unique_together={('campaign', 'participant')},
        ),
    ]
