# Generated by Django 5.0.1 on 2025-11-05 10:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveys", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="surveycampaign",
            name="allow_multiple_responses",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="surveycampaign",
            name="auto_approve_participants",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="surveycampaign",
            name="average_completion_time",
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="surveycampaign",
            name="max_responses_per_user",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="surveycampaign",
            name="priority",
            field=models.CharField(
                choices=[
                    ("low", "Low"),
                    ("normal", "Normal"),
                    ("high", "High"),
                    ("urgent", "Urgent"),
                ],
                default="normal",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="surveycampaign",
            name="require_approval",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="surveycampaign",
            name="response_quality_score",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="surveycampaign",
            name="review_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="surveycampaign",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="surveycampaign",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_campaigns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="surveycampaign",
            name="scheduled_end",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="surveycampaign",
            name="scheduled_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="surveycampaign",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="surveycampaign",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("review", "Under Review"),
                    ("approved", "Approved"),
                    ("active", "Active"),
                    ("paused", "Paused"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("rejected", "Rejected"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CampaignAnalytics",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("total_views", models.PositiveIntegerField(default=0)),
                ("total_clicks", models.PositiveIntegerField(default=0)),
                (
                    "conversion_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("average_response_time", models.DurationField(blank=True, null=True)),
                (
                    "completion_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "dropout_rate",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "participant_demographics",
                    models.JSONField(blank=True, default=dict),
                ),
                ("geographic_distribution", models.JSONField(blank=True, default=dict)),
                (
                    "peak_participation_hours",
                    models.JSONField(blank=True, default=list),
                ),
                (
                    "daily_participation_trend",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "response_quality_distribution",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "satisfaction_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "cost_per_response",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "roi_score",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="surveys.surveycampaign",
                    ),
                ),
            ],
            options={
                "db_table": "campaign_analytics",
            },
        ),
        migrations.CreateModel(
            name="CampaignTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("academic", "Academic Research"),
                            ("market", "Market Research"),
                            ("social", "Social Studies"),
                            ("health", "Health & Wellness"),
                            ("technology", "Technology"),
                            ("education", "Education"),
                            ("general", "General Survey"),
                        ],
                        default="general",
                        max_length=50,
                    ),
                ),
                ("survey_config", models.JSONField(default=dict)),
                ("default_settings", models.JSONField(blank=True, default=dict)),
                ("eligibility_criteria", models.JSONField(blank=True, default=dict)),
                ("is_public", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                ("usage_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_campaign_templates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "campaign_templates",
                "ordering": ["-usage_count", "-created_at"],
            },
        ),
        migrations.AddField(
            model_name="surveycampaign",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="campaigns",
                to="surveys.campaigntemplate",
            ),
        ),
        migrations.CreateModel(
            name="CampaignMilestone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "milestone_type",
                    models.CharField(
                        choices=[
                            ("participants_25", "25% Participants Reached"),
                            ("participants_50", "50% Participants Reached"),
                            ("participants_75", "75% Participants Reached"),
                            ("participants_100", "100% Participants Reached"),
                            ("responses_25", "25% Responses Completed"),
                            ("responses_50", "50% Responses Completed"),
                            ("responses_75", "75% Responses Completed"),
                            ("responses_100", "100% Responses Completed"),
                            ("duration_25", "25% Duration Elapsed"),
                            ("duration_50", "50% Duration Elapsed"),
                            ("duration_75", "75% Duration Elapsed"),
                            ("duration_100", "100% Duration Elapsed"),
                        ],
                        max_length=50,
                    ),
                ),
                ("target_value", models.PositiveIntegerField()),
                ("current_value", models.PositiveIntegerField()),
                ("is_achieved", models.BooleanField(default=False)),
                ("achieved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="surveys.surveycampaign",
                    ),
                ),
            ],
            options={
                "db_table": "campaign_milestones",
                "indexes": [
                    models.Index(
                        fields=["campaign", "is_achieved"],
                        name="campaign_mi_campaig_7316fe_idx",
                    )
                ],
                "unique_together": {("campaign", "milestone_type")},
            },
        ),
        migrations.CreateModel(
            name="CampaignNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("campaign_launched", "Campaign Launched"),
                            ("campaign_completed", "Campaign Completed"),
                            ("participant_joined", "Participant Joined"),
                            ("response_submitted", "Response Submitted"),
                            ("reward_processed", "Reward Processed"),
                            ("campaign_paused", "Campaign Paused"),
                            ("campaign_cancelled", "Campaign Cancelled"),
                            ("milestone_reached", "Milestone Reached"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("data", models.JSONField(blank=True, default=dict)),
                ("is_read", models.BooleanField(default=False)),
                ("is_sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="surveys.surveycampaign",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "campaign_notifications",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "is_read"],
                        name="campaign_no_recipie_571750_idx",
                    ),
                    models.Index(
                        fields=["campaign", "notification_type"],
                        name="campaign_no_campaig_254d19_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="campaigntemplate",
            index=models.Index(
                fields=["category", "is_public"], name="campaign_te_categor_4c3fac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaigntemplate",
            index=models.Index(
                fields=["is_featured", "-usage_count"],
                name="campaign_te_is_feat_1c5498_idx",
            ),
        ),
    ]
