# Generated by Django 5.0.1 on 2025-11-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='data_collection',
            field=models.JSONField(blank=True, default=dict, help_text='Data collection configuration including survey settings and participant criteria'),
        ),
        migrations.AddField(
            model_name='project',
            name='progress_tracking',
            field=models.JSONField(blank=True, default=dict, help_text='Detailed progress tracking with milestones and publication status'),
        ),
        migrations.AddField(
            model_name='project',
            name='research_design',
            field=models.JSONField(blank=True, default=dict, help_text='Research design configuration including theoretical models, variables, and hypotheses'),
        ),
    ]
