# Generated by Django 5.0.1 on 2025-11-06 04:18

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                ("color", models.CharField(default="#10B981", max_length=7)),
                ("post_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MediaTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="BlogCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("color", models.CharField(default="#3B82F6", max_length=7)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("meta_title", models.CharField(blank=True, max_length=60)),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                ("post_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="blog.blogcategory",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Blog Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=255,
                        validators=[django.core.validators.MinLengthValidator(10)],
                    ),
                ),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("content", models.TextField()),
                ("excerpt", models.TextField(blank=True, max_length=300)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("review", "Under Review"),
                            ("scheduled", "Scheduled"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "meta_title",
                    models.CharField(
                        blank=True,
                        max_length=60,
                        validators=[django.core.validators.MaxLengthValidator(60)],
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        max_length=160,
                        validators=[django.core.validators.MaxLengthValidator(160)],
                    ),
                ),
                ("focus_keyword", models.CharField(blank=True, max_length=100)),
                ("canonical_url", models.URLField(blank=True)),
                ("og_title", models.CharField(blank=True, max_length=60)),
                ("og_description", models.CharField(blank=True, max_length=160)),
                ("twitter_title", models.CharField(blank=True, max_length=60)),
                ("twitter_description", models.CharField(blank=True, max_length=160)),
                ("word_count", models.IntegerField(default=0)),
                ("reading_time", models.IntegerField(default=0)),
                ("seo_score", models.IntegerField(default=0)),
                ("readability_score", models.FloatField(default=0)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("view_count", models.IntegerField(default=0)),
                ("like_count", models.IntegerField(default=0)),
                ("share_count", models.IntegerField(default=0)),
                ("comment_count", models.IntegerField(default=0)),
                (
                    "search_vector",
                    django.contrib.postgres.search.SearchVectorField(null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blog_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="posts", to="blog.blogcategory"
                    ),
                ),
                (
                    "collaborators",
                    models.ManyToManyField(
                        blank=True,
                        related_name="collaborated_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="posts", to="blog.blogtag"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BlogComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content", models.TextField()),
                ("is_approved", models.BooleanField(default=True)),
                ("is_spam", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="blog.blogcomment",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="blog.blogpost",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MediaFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filename", models.CharField(max_length=255)),
                ("original_name", models.CharField(max_length=255)),
                ("mime_type", models.CharField(max_length=100)),
                ("file_size", models.BigIntegerField()),
                ("storage_path", models.CharField(max_length=500)),
                ("cdn_url", models.URLField(blank=True)),
                ("width", models.IntegerField(blank=True, null=True)),
                ("height", models.IntegerField(blank=True, null=True)),
                ("alt_text", models.TextField(blank=True)),
                ("caption", models.TextField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("ai_description", models.TextField(blank=True)),
                ("ai_tags", models.JSONField(default=list)),
                ("detected_objects", models.JSONField(default=list)),
                ("usage_count", models.IntegerField(default=0)),
                ("last_used", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="blogpost",
            name="featured_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="featured_posts",
                to="blog.mediafile",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="og_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="og_posts",
                to="blog.mediafile",
            ),
        ),
        migrations.AddField(
            model_name="blogpost",
            name="twitter_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="twitter_posts",
                to="blog.mediafile",
            ),
        ),
        migrations.CreateModel(
            name="MediaFolder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="blog.mediafolder",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="mediafile",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.mediafolder",
            ),
        ),
        migrations.AddField(
            model_name="mediafile",
            name="tags",
            field=models.ManyToManyField(blank=True, to="blog.mediatag"),
        ),
        migrations.CreateModel(
            name="SEOAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("overall_score", models.IntegerField(default=0)),
                ("title_score", models.IntegerField(default=0)),
                ("description_score", models.IntegerField(default=0)),
                ("content_score", models.IntegerField(default=0)),
                ("keyword_score", models.IntegerField(default=0)),
                ("readability_score", models.FloatField(default=0)),
                ("technical_score", models.IntegerField(default=0)),
                ("focus_keyword", models.CharField(blank=True, max_length=100)),
                ("keyword_density", models.FloatField(default=0)),
                ("keyword_distribution", models.JSONField(default=dict)),
                ("related_keywords", models.JSONField(default=list)),
                ("flesch_kincaid_score", models.FloatField(default=0)),
                ("gunning_fog_score", models.FloatField(default=0)),
                ("coleman_liau_score", models.FloatField(default=0)),
                ("sentence_count", models.IntegerField(default=0)),
                ("paragraph_count", models.IntegerField(default=0)),
                ("internal_links", models.IntegerField(default=0)),
                ("external_links", models.IntegerField(default=0)),
                ("images_without_alt", models.IntegerField(default=0)),
                ("heading_structure", models.JSONField(default=dict)),
                ("suggestions", models.JSONField(default=list)),
                ("competitor_data", models.JSONField(default=dict)),
                ("analyzed_at", models.DateTimeField(auto_now=True)),
                (
                    "post",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seo_analysis",
                        to="blog.blogpost",
                    ),
                ),
            ],
            options={
                "verbose_name": "SEO Analysis",
                "verbose_name_plural": "SEO Analyses",
            },
        ),
        migrations.CreateModel(
            name="BlogAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("page_views", models.IntegerField(default=0)),
                ("unique_visitors", models.IntegerField(default=0)),
                ("bounce_rate", models.FloatField(default=0)),
                ("avg_time_on_page", models.IntegerField(default=0)),
                ("likes", models.IntegerField(default=0)),
                ("shares", models.IntegerField(default=0)),
                ("comments", models.IntegerField(default=0)),
                ("facebook_shares", models.IntegerField(default=0)),
                ("twitter_shares", models.IntegerField(default=0)),
                ("linkedin_shares", models.IntegerField(default=0)),
                ("organic_traffic", models.IntegerField(default=0)),
                ("search_impressions", models.IntegerField(default=0)),
                ("search_clicks", models.IntegerField(default=0)),
                ("avg_position", models.FloatField(default=0)),
                ("date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="blog.blogpost",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("post", "date")},
            },
        ),
        migrations.CreateModel(
            name="BlogPostVersion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("version_number", models.IntegerField()),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("excerpt", models.TextField(blank=True)),
                ("change_summary", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="blog.blogpost",
                    ),
                ),
            ],
            options={
                "ordering": ["-version_number"],
                "unique_together": {("post", "version_number")},
            },
        ),
        migrations.AddIndex(
            model_name="blogpost",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="blog_blogpo_search__5f1e86_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="blogpost",
            index=models.Index(
                fields=["status", "published_at"], name="blog_blogpo_status_aa5436_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="blogpost",
            index=models.Index(
                fields=["author", "created_at"], name="blog_blogpo_author__8af930_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="blogpost",
            index=models.Index(fields=["slug"], name="blog_blogpo_slug_361555_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="mediafolder",
            unique_together={("name", "parent")},
        ),
    ]
