# Generated by Django 5.0.1 on 2025-11-05 10:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Permission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("codename", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("users", "User Management"),
                            ("campaigns", "Campaign Management"),
                            ("rewards", "Reward Management"),
                            ("analytics", "Analytics & Reports"),
                            ("system", "System Administration"),
                            ("content", "Content Management"),
                            ("security", "Security Management"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_system", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Permission",
                "verbose_name_plural": "Permissions",
                "db_table": "permissions",
                "ordering": ["category", "name"],
                "indexes": [
                    models.Index(
                        fields=["category", "is_active"],
                        name="permissions_categor_cbf739_idx",
                    ),
                    models.Index(
                        fields=["codename"], name="permissions_codenam_5f0327_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("permissions", models.JSONField(blank=True, default=list)),
                ("is_system", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("priority", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Role",
                "verbose_name_plural": "User Roles",
                "db_table": "user_roles",
                "ordering": ["-priority", "name"],
            },
        ),
        migrations.CreateModel(
            name="UserRoleAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "assigned_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_assignments",
                        to="admin_management.userrole",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="role_assignments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Role Assignment",
                "verbose_name_plural": "User Role Assignments",
                "db_table": "user_role_assignments",
            },
        ),
        migrations.CreateModel(
            name="AdminActivity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("user_created", "User Created"),
                            ("user_updated", "User Updated"),
                            ("user_suspended", "User Suspended"),
                            ("user_activated", "User Activated"),
                            ("user_deleted", "User Deleted"),
                            ("user_role_changed", "User Role Changed"),
                            ("user_impersonated", "User Impersonated"),
                            ("config_updated", "Configuration Updated"),
                            ("system_settings_changed", "System Settings Changed"),
                            ("brand_config_updated", "Brand Configuration Updated"),
                            ("fee_config_updated", "Fee Configuration Updated"),
                            ("campaign_approved", "Campaign Approved"),
                            ("campaign_rejected", "Campaign Rejected"),
                            ("campaign_forced_complete", "Campaign Force Completed"),
                            ("campaign_cancelled", "Campaign Cancelled"),
                            ("reward_processed", "Reward Processed"),
                            ("reward_rejected", "Reward Rejected"),
                            ("bulk_rewards_processed", "Bulk Rewards Processed"),
                            ("security_alert_resolved", "Security Alert Resolved"),
                            ("access_granted", "Access Granted"),
                            ("access_revoked", "Access Revoked"),
                            ("audit_log_exported", "Audit Log Exported"),
                            ("system_backup_created", "System Backup Created"),
                            ("system_restored", "System Restored"),
                            ("maintenance_mode_enabled", "Maintenance Mode Enabled"),
                            ("maintenance_mode_disabled", "Maintenance Mode Disabled"),
                        ],
                        max_length=100,
                    ),
                ),
                ("description", models.TextField()),
                ("object_id", models.CharField(blank=True, max_length=255, null=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "admin_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admin_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin Activity",
                "verbose_name_plural": "Admin Activities",
                "db_table": "admin_activities",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["admin_user", "-created_at"],
                        name="admin_activ_admin_u_33e85e_idx",
                    ),
                    models.Index(
                        fields=["action_type", "-created_at"],
                        name="admin_activ_action__5c2b99_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="admin_activ_content_9c9d06_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BrandConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("platform_title", models.CharField(default="NCSKIT", max_length=255)),
                ("platform_tagline", models.TextField(blank=True)),
                ("meta_description", models.TextField(blank=True)),
                ("header_logo_url", models.URLField(blank=True)),
                ("favicon_url", models.URLField(blank=True)),
                ("mobile_icon_url", models.URLField(blank=True)),
                ("email_logo_url", models.URLField(blank=True)),
                ("color_scheme", models.JSONField(blank=True, default=dict)),
                (
                    "theme",
                    models.CharField(
                        choices=[
                            ("light", "Light Theme"),
                            ("dark", "Dark Theme"),
                            ("auto", "Auto (System Preference)"),
                        ],
                        default="light",
                        max_length=50,
                    ),
                ),
                ("custom_css", models.TextField(blank=True)),
                ("custom_js", models.TextField(blank=True)),
                ("social_image_url", models.URLField(blank=True)),
                ("twitter_handle", models.CharField(blank=True, max_length=50)),
                ("facebook_page", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=False)),
                ("version", models.CharField(default="1.0", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_brand_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Brand Configuration",
                "verbose_name_plural": "Brand Configurations",
                "db_table": "brand_configurations",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "-created_at"],
                        name="brand_confi_is_acti_94f190_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SystemConfiguration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(max_length=255, unique=True)),
                ("value", models.JSONField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("general", "General Settings"),
                            ("security", "Security Settings"),
                            ("email", "Email Settings"),
                            ("payment", "Payment Settings"),
                            ("features", "Feature Toggles"),
                            ("limits", "System Limits"),
                            ("branding", "Branding Settings"),
                        ],
                        default="general",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("string", "String"),
                            ("integer", "Integer"),
                            ("float", "Float"),
                            ("boolean", "Boolean"),
                            ("json", "JSON Object"),
                            ("array", "Array"),
                        ],
                        default="string",
                        max_length=20,
                    ),
                ),
                ("validation_rules", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("is_system", models.BooleanField(default=False)),
                ("requires_restart", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="updated_configs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "System Configuration",
                "verbose_name_plural": "System Configurations",
                "db_table": "system_configurations",
                "ordering": ["category", "key"],
                "indexes": [
                    models.Index(
                        fields=["category", "is_active"],
                        name="system_conf_categor_eb7070_idx",
                    ),
                    models.Index(fields=["key"], name="system_conf_key_35f9ec_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserLoginHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField()),
                ("device_info", models.JSONField(blank=True, default=dict)),
                ("location_info", models.JSONField(blank=True, default=dict)),
                ("session_key", models.CharField(blank=True, max_length=255)),
                ("login_at", models.DateTimeField(auto_now_add=True)),
                ("logout_at", models.DateTimeField(blank=True, null=True)),
                ("session_duration", models.DurationField(blank=True, null=True)),
                ("is_successful", models.BooleanField(default=True)),
                ("failure_reason", models.CharField(blank=True, max_length=255)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Login History",
                "verbose_name_plural": "User Login History",
                "db_table": "user_login_history",
                "ordering": ["-login_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "-login_at"],
                        name="user_login__user_id_20fbc4_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "-login_at"],
                        name="user_login__ip_addr_9b9362_idx",
                    ),
                    models.Index(
                        fields=["is_successful", "-login_at"],
                        name="user_login__is_succ_122855_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(
                fields=["is_active", "-priority"], name="user_roles_is_acti_74026a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userroleassignment",
            index=models.Index(
                fields=["user", "is_active"], name="user_role_a_user_id_c7b2be_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userroleassignment",
            index=models.Index(
                fields=["role", "is_active"], name="user_role_a_role_id_5faa79_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userroleassignment",
            unique_together={("user", "role")},
        ),
    ]
