# Generated by Django 5.0.1 on 2025-11-05 08:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchVariable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('variable_type', models.CharField(choices=[('independent', 'Independent Variable'), ('dependent', 'Dependent Variable'), ('mediator', 'Mediator Variable'), ('moderator', 'Moderator Variable'), ('control', 'Control Variable')], max_length=20)),
                ('measurement_scale', models.CharField(choices=[('nominal', 'Nominal'), ('ordinal', 'Ordinal'), ('interval', 'Interval'), ('ratio', 'Ratio'), ('likert', 'Likert Scale')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'research_variables',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QuestionTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[('text', 'Text Input'), ('number', 'Number Input'), ('email', 'Email Input'), ('choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice'), ('likert', 'Likert Scale'), ('rating', 'Rating Scale'), ('boolean', 'Yes/No'), ('date', 'Date'), ('time', 'Time'), ('datetime', 'Date and Time'), ('file', 'File Upload'), ('matrix', 'Matrix/Grid')], max_length=20)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('is_required', models.BooleanField(default=True)),
                ('validation_rules', models.JSONField(blank=True, default=dict)),
                ('usage_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('research_variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_templates', to='question_bank.researchvariable')),
            ],
            options={
                'db_table': 'question_templates',
                'ordering': ['-usage_count', 'text'],
            },
        ),
        migrations.CreateModel(
            name='TheoreticalModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'theoretical_models',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='researchvariable',
            name='theoretical_models',
            field=models.ManyToManyField(related_name='variables', to='question_bank.theoreticalmodel'),
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('questions', models.ManyToManyField(related_name='question_banks', to='question_bank.questiontemplate')),
                ('theoretical_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_banks', to='question_bank.theoreticalmodel')),
            ],
            options={
                'db_table': 'question_banks',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QuestionUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_id', models.UUIDField(blank=True, null=True)),
                ('survey_id', models.UUIDField(blank=True, null=True)),
                ('used_at', models.DateTimeField(auto_now_add=True)),
                ('modifications', models.JSONField(blank=True, default=dict)),
                ('question_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_logs', to='question_bank.questiontemplate')),
                ('used_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'question_usage_logs',
                'ordering': ['-used_at'],
                'indexes': [models.Index(fields=['question_template', '-used_at'], name='question_us_questio_a47598_idx'), models.Index(fields=['used_by', '-used_at'], name='question_us_used_by_7dd104_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='questiontemplate',
            index=models.Index(fields=['question_type'], name='question_te_questio_dc59db_idx'),
        ),
        migrations.AddIndex(
            model_name='questiontemplate',
            index=models.Index(fields=['research_variable'], name='question_te_researc_a3f8eb_idx'),
        ),
        migrations.AddIndex(
            model_name='questiontemplate',
            index=models.Index(fields=['-usage_count'], name='question_te_usage_c_a268ca_idx'),
        ),
        migrations.AddIndex(
            model_name='theoreticalmodel',
            index=models.Index(fields=['category'], name='theoretical_categor_476ac1_idx'),
        ),
        migrations.AddIndex(
            model_name='theoreticalmodel',
            index=models.Index(fields=['name'], name='theoretical_name_560f97_idx'),
        ),
        migrations.AddIndex(
            model_name='researchvariable',
            index=models.Index(fields=['variable_type'], name='research_va_variabl_708c69_idx'),
        ),
        migrations.AddIndex(
            model_name='researchvariable',
            index=models.Index(fields=['measurement_scale'], name='research_va_measure_3efe55_idx'),
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['theoretical_model'], name='question_ba_theoret_6e8d47_idx'),
        ),
        migrations.AddIndex(
            model_name='questionbank',
            index=models.Index(fields=['is_public'], name='question_ba_is_publ_17289c_idx'),
        ),
    ]
